version: "3"
services:
  zeus-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/1-tables.sql
    networks:
      - zeus

volumes:
  database_postgres:

networks:
  zeus:
    driver: bridge
