version: "3"
services:
  app:
    container_name: zeus_app
    build: ""
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api:/usr/src/app/
    networks:
      - sql_zeus

volumes:
  api:

networks:
  sql_zeus:
    external: true
